import {StyleSheet} from 'react-native';
export const style = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    width: '100%',
    height: 44,
    backgroundColor: 'rgba(10, 186, 181, 1)',
  },
  subHeaderView: {
    marginHorizontal: 20,
  },
  dateText: {
    fontWeight: '700',
    fontStyle: 'normal',
    fontSize: 13,
    lineHeight: 16.25,
    letterSpacing: 1,
    marginTop: 25,
    color: 'rgba(154, 154, 154, 1)',
    height: 16,
  },
  nameText: {
    fontSize: 28,
    lineHeight: 35,
    color: 'rgba(42, 42, 42, 1)',
    marginTop: 10,
    height: 35,
  },
  text: {
    fontWeight: '700',
    fontStyle: 'normal',
    fontSize: 15,
    lineHeight: 18.75,
    letterSpacing: 1,
    height: 19,
    marginTop: 10,
    color: 'rgba(58, 58, 58, 1)',
  },
  hairline: {
    backgroundColor: 'rgba(238, 238, 238, 1)',
    borderWidth: 0.3,
    width: '100%',
    marginTop: 25,
  },
  forgotView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 25,
  },
  forgotText: {
    fontWeight: '500',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 17.5,
    letterSpacing: 0.03,

    color: 'rgba(42, 42, 42, 1)',
    height: 18,
  },
  clearText: {
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 15,
    letterSpacing: 0.03,
    height: 15,
    color: '#0ABAB5',
  },
  meetMainView: {
    width: '100%',
    height: 60,
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    marginTop: 18,
  },
  meetIcon: {
    marginLeft: 16,
    marginTop: 16,
  },
  meetText: {
    fontWeight: '500',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 20,
    letterSpacing: 0.03,
    marginTop: 20,
    marginLeft: 16,
    color: 'rgba(58, 58, 58, 1)',
  },
  meetTime: {
    fontSize: 14,
    fontStyle: 'normal',
    lineHeight: 17.5,
    letterSpacing: 0.03,
    color: 'rgba(154, 154, 154, 1)',
    marginTop: 22,
    marginRight: 16,
  },
  meetFirstView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  meetSecoundView: {
    flexDirection: 'row',
  },
  fListView: {
    marginLeft: 20,
  },
  fListTitle: {
    fontSize: 16,
    letterSpacing: 0.03,
    lineHeight: 20,
    fontStyle: 'normal',
    fontWeight: '500',
    marginTop: 25,
    color: '#2A2A2A',
  },
  meetCard: {
    width: 140,
    height: 202,
    backgroundColor: '#EE4A5E',
    borderRadius: 15,
  },
  meetcard2: {
    backgroundColor: '#009E9A',
    marginLeft: 30,
  },
  meetCardIcon: {
    marginTop: 20,
    alignSelf: 'center',
  },
  qrIcon: {
    width: 80,
    height: 80,
    marginTop: 30,
  },
  cardHairline: {
    width: 100,
    marginTop: 20,
    marginLeft: 20,
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  cardText: {
    fontSize: 18,
    fontStyle: 'normal',
    lineHeight: 22.5,
    letterSpacing: 0.03,
    color: 'rgba(255, 255, 255, 1) ',
    textAlign: 'center',
    marginTop: 18,
    fontWeight: '700',
  },
  meetCardView: {
    width: 355,
    height: 222,
    flexDirection: 'row',
    marginLeft: 20,
    marginTop: 20,
  },
  meetcardView2: {
    marginLeft: 0,
  },
  checkUpView: {
    width: 355,
    height: 150,
    marginTop: 20,
    flexDirection: 'row',
  },
  checkUpCard: {
    backgroundColor: '#EF7319',
    width: 307,
    height: 130,
    marginLeft: 20,
    marginTop: 10,
    borderRadius: 15,
    flexDirection: 'row',
  },
  checkUpCard2: {
    marginLeft: 50,
    backgroundColor: '#0085FF',
  },
  checkCardIcon: {
    marginTop: 20,
    marginLeft: 20,
  },
  checkCardText: {
    marginTop: 30,
    marginLeft: 20,
  },
  checkCardText2: {
    color: '#FFFFFF',
    marginTop: 5,
    marginLeft: 20,
  },
  checkCardIcon2: {
    marginLeft: 39,
    marginTop: 90,
  },
  left: {
    marginLeft: 14,
  },
});
