import {StyleSheet} from 'react-native';
export const style = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    backgroundColor: '#FFFFFF',
  },
  header: {
    width: '100%',
    height: 44,
    backgroundColor: 'rgba(10, 186, 181, 1)',
  },
  covidImg1: {
    marginTop: 20,
    alignSelf: 'center',
  },

  checkUpCard: {
    backgroundColor: 'rgba(238, 74, 94, 1)',
    height: 130,
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 15,
    flexDirection: 'row',
  },
  checkCardIcon: {
    marginTop: 15,
    marginLeft: 15,
  },
  checkCardText: {
    marginTop: 15,
    marginLeft: 15,
    fontWeight: '700',
    fontStyle: 'normal',
    fontSize: 18,
    lineHeight: 22.5,
    letterSpacing: 0.03,
    color: 'rgba(255, 255, 255, 1)',
  },
  checkCardText2: {
    color: 'rgba(255, 255, 255, 1)',
    marginTop: 5,
    marginLeft: 15,
    fontSize: 14,
    fontWeight: '500',
    width: 215,
  },
  checkCardIcon2: {
    marginTop: 90,
    marginLeft: -16,
  },
  stepsView: {
    marginHorizontal: 20,
    marginTop: 25,
  },
  stepsTitle: {
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 18.75,
    letterSpacing: 0.03,
    color: '#2A2A2A',
  },
  stepsCard: {
    width: '100%',
    height: 111,
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 1,
    flexDirection: 'row',
    marginBottom: 5,
  },
  stepsImg1: {
    marginTop: 10,
    marginLeft: 10,
  },
  stepsCardTitle: {
    fontWeight: '700',
    lineHeight: 17.5,
    fontSize: 14,
    letterSpacing: 0.03,
    color: 'rgba(58, 58, 58, 1)',
    marginLeft: 10,
    marginTop: 10,
    width: 139,
    height: 18,
  },
  stepsCardPara: {
    fontSize: 10,
    fontWeight: '500',
    lineHeight: 18,
    letterSpacing: 0.02,
    width: 215,
    height: 44,
    marginTop: 10,
    marginLeft: 10,
    color: 'rgba(154, 154, 154, 1)',
  },
  learnMoreText: {
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.02,
    color: 'rgba(10, 186, 181, 1)',
    paddingBottom: 10,
    alignSelf: 'flex-end',
    marginRight: 20,
  },
});
